# Generated by Django 4.2 on 2023-04-06 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Faso_Shops', '0002_categorys_produits_delete_category_delete_produit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorys',
            new_name='Categorie',
        ),
        migrations.RenameModel(
            old_name='Produits',
            new_name='Produit',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='category',
            new_name='categorie',
        ),
    ]
