# Generated by Django 4.2 on 2023-05-06 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Faso_Shops', '0003_rename_categorys_categorie_rename_produits_produit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=500)),
                ('nom', models.CharField(max_length=500)),
                ('prenom', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('ville', models.CharField(max_length=300)),
                ('pays', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=20)),
                ('date_commande', models.DateTimeField(auto_now=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faso_Shops.produit')),
            ],
            options={
                'ordering': ['-date_commande'],
            },
        ),
    ]
