# Generated by Django 4.2 on 2023-05-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faso_Shops', '0006_commande_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='static/album')),
                ('date_pagne', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_pagne'],
            },
        ),
        migrations.CreateModel(
            name='Pretporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='static/album')),
                ('date_pret', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_pret'],
            },
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(upload_to='static/album'),
        ),
    ]
