# Generated by Django 4.2 on 2023-05-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faso_Shops', '0008_alter_produit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(upload_to='C:/Users/del/Desktop/Projet_DI/mon_projetDI_root/Faso_Shops/static/album'),
        ),
    ]
